//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySpiders
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Kolekcja
    {
        public int ID { get; set; }
        public string Gatunek { get; set; }
        [DisplayName ("Iloœæ posiadanych sztuk")]
        public string Ilosc_posiadanych_sztuk { get; set; }
        [DisplayName("Stadium paj¹ka w cm")]
        public string Stadium_pajaka_w_cm { get; set; }
        [DisplayName("Cena za jedn¹ sztukê")]
        public string Cena_za_jedna_sztuke { get; set; }
    }
}
